# -*- coding: utf-8 -*-
"""Ass 2-Datas structures python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HNnjclh2stUeWfBaUOSmMZ8s2YsdUwoI

# Assignment 2-Data structures in python

# **LIST**
"""

numbers=[1,2,3,4,5]
print(numbers)

numbers.append(9)
numbers.append(7)
numbers.append(10)
print(numbers)

print("List Elements:")
for number in numbers:
    print(number)

"""# **DICTIONARY**"""

person = {'name': 'John', 'age': 25, 'address': 'New York'}
print("Dictionary:", person)

person['phone'] = '1234567890'
print("Updated Dictionary:", person)



"""## SET"""

my_set = {1, 2, 3, 4, 5}
print("Set:", my_set)

my_set.add(6)
print("Set after adding 6:", my_set)

my_set.remove(3)
print("Set after removing 3:", my_set)



"""## TUPLE"""

my_tuple = (1, 2, 3, 4)
print("Tuple:", my_tuple)

print("Length of the tuple:", len(my_tuple))

